name: Docker Hub

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1.2.0

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch      

    - name: Build and Push Docker Image
      # See https://github.com/marketplace/actions/docker-push
      uses: opspresso/action-docker@master
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "sslhep/servicex_code_gen_funcadl_xaod"
        LATEST: FALSE
        TAG_NAME: ${{ steps.extract_branch.outputs.branch }}
