name: Docker Hub

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1.2.0
    - name: Build and Push Docker Image
      # See https://github.com/marketplace/actions/docker-push
      uses: opspresso/action-docker@master
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "gordonwatts/servicex_code_gen_funcadl_xaod"
        LATEST: "true"
