name: Docker Hub

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1.2.0

    - name: Build Uproot Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        dockerfile: Dockerfile.uprootTransformer
        name: sslhep/servicex_func_adl_uproot_transformer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: "${GITHUB_REF##*/}"

    - name: Build xAOD Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        dockerfile: Dockerfile.xaodTransformer
        name: sslhep/servicex_func_adl_xaod_transformer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: "${GITHUB_REF##*/}"

